name: unit test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      db:
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: test_neodb
        ports:
          - 5432:5432
      db2:
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: test_neodb_takahe
        ports:
          - 15432:5432
      typesense:
        image: typesense/typesense:29.0
        env:
          TYPESENSE_API_KEY: testpass
          TYPESENSE_DATA_DIR: /data
        ports:
          - 8108:8108
        volumes:
          - ts_data:/data
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install Dependencies
      run: |
        uv sync
        sudo apt install -y gettext
    - name: Run Tests
      env:
        NEODB_SECRET_KEY: test
        NEODB_SITE_NAME: test
        NEODB_SITE_DOMAIN: example.org
        NEODB_DB_URL: postgres://testuser:testpass@127.0.0.1/test_neodb
        TAKAHE_DB_URL: postgres://testuser:testpass@127.0.0.1/test_neodb_takahe
        NEODB_REDIS_URL: redis://127.0.0.1:6379/0
        NEODB_SEARCH_URL: typesense://testuser:testpass@127.0.0.1:8108/cat
      run: |
        uv run manage.py compilemessages -i .venv -l zh_Hans
        uv run pytest
